### PR TITLE
Fix SceneView UI layout issues with 2021.2+

### LINKED ISSUE #318: [Bug] Realtime CSG overlay breaks scene overlay windows
I noticed that scene overlay windows (tools window, particle system window, etc.) won't receive any GUI events while the realtime CSG overlay window is open. Here is a gif that showcases the issue:
NqYVtuxIdX
Once I close the realtime CSG window and it jumps back into overlay mode the click is not registered anymore on the particle overlay window but instead the click goes through the window and deselects the particle system. I tested several other overlay windows so it is not just the particle window.

I am using the latest version from master with Unity 2020.2.0f1.

### LINKED ISSUE #327: Bottom bar partially or totally hidden on 2021.2
image

Steps to reproduce:

- Create a new 2021.2.3f1 project
- Import RealtimeCSG from the Asset Store
- Open the RealtimeCSG GUI

Tried to resize but it's still hidden.
If you place the Tools bar on the bottom, it's gonna be completely hidden. 

image

### PR DESCRIPTION
**Pull request by Kerfuffles**
This PR should resolve #327, and should self-adjust to any docked overlay toolbars automatically. It also fixes the scene info overlay in the same way, as it also relied on `SceneView.postion` to get the width/height of the scene view. The new method should use `SceneView.rootVisualElement.contentRect` instead, which accounts for any docked overlays, etc.. This PR does NOT fix the issue of overlays blocking the RCSG windows/toolbar, nor does it fix #318

### CODE REVIEW

**Comment by Kerfuffles** [comment]
In the future, it may be worthwhile to re-visit this and provide an actual proper fix (actually use overlays), so that there are no overlapping windows or other problems going forward. It *should* theoretically be possible to just call the IMGUI code inside of an overlay, instead of rewriting the entire thing. Just some thoughts.

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs [hunk 1]
```diff
@@ -70,8 +70,8 @@ internal static void OnScene(SceneView sceneView)
 				TooltipUtility.InitToolTip(sceneView);
 				if (Event.current.type == EventType.Repaint)
 				{
-					SceneViewBottomBarGUI.ShowGUI(sceneView);
-                	SceneViewInfoGUI.DrawInfoGUI( sceneView );
+					//SceneViewBottomBarGUI.ShowGUI(sceneView);
+                	//SceneViewInfoGUI.DrawInfoGUI( sceneView );
```
Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs:74]: I vaguely remember this was a Unity bug workaround .. so might need an ifdef around it (if it's been fixed in unity)

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs [hunk 2]
```diff
@@ -64,9 +64,10 @@ void Initialize()
 			EditorApplication.hierarchyWindowChanged	+= OnHierarchyWindowChanged;
 #endif
 
-#if UNITY_2018_3_OR_NEWER
+#if UNITY_2018_3_OR_NEWER && !UNITY_2020_1_OR_NEWER
```
Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs:67]: what about < 2018.3 ?

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeManager.cs [hunk 3]
```diff
@@ -517,7 +517,7 @@ public static void OnSceneGUI(SceneView sceneView)
 					if (RealtimeCSG.CSGSettings.EnableRealtimeCSG)
 					{
 						// handle the tool
-						var sceneSize = sceneView.position.size;
+						var sceneSize = sceneView.rootVisualElement.contentRect;
```
Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeManager.cs:520]: you might want to guard this with an ifdef for users of older unity versions, not sure when this was introduced ..

**Comment by HeadClot** [comment]
Hey, I am running into an issue with this PR. I cannot draw out any form of CSG Shapes. Is anyone else running into this issue?

I am on Unity 2021.2.7f1 and I am getting no errors.

**Comment by andreiagmu** [comment]
@Kerfuffles @LogicalError I'm having the same issue with this PR that @HeadClot commented above.
I'm testing in Unity 2021.2.6f1, and I can't draw any CSG Shape in the viewport.
In the Master branch, the shapes drawing works correctly.

**Comment by andreiagmu** [comment]
I fixed the issue, line 520 from EditModeManager.cs should be
`var sceneSize = sceneView.position.size;`
like in the master branch.

Now RCSG is working properly on Unity 2021.2 here :)

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs (hunk 1 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs]: do you know what version this may have been introduced in?

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs (hunk 2 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs:67]: this is how it was written already, so im not sure what you mean?

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeManager.cs (hunk 3 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeManager.cs]: this specific part was reverted back to master as it caused breaking changes as was mentioned by @HeadClot and @andreiagmu.

**Comment by Kerfuffles** [comment]
> I fixed the issue, line 520 from EditModeManager.cs should be `var sceneSize = sceneView.position.size;` like in the master branch.
> 
> Now RCSG is working properly on Unity 2021.2 here :)

This did indeed fix the issue! Thanks for that! In addition to those changes, I changed the sliders in the sphere and cylinder generators, to buttons, which is a change I had done in my own personal project as a workaround to the buggy input with sliders in the scene view.

**Comment by HeadClot** [comment]
Cannot wait to see this merged :)

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs (hunk 2 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/UpdateLoop.cs]: i realized what you had meant with this, and it has been fixed with the latest commit

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs (hunk 1 above)
Comment (LogicalError) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs]: I'm guessing the version that introduced the new sceneview UI stuff might've changed things, so might be better to keep things the way they were for earlier unity versions, and switch to the new things for versions after

**Comment by LogicalError** [comment]
Actually, I'm not sure if it's a good idea to commit all the ProjectSettings assets + ProjectVersion.txt since that will cause problems with older versions of unity

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs [hunk 4]
```diff
@@ -10,10 +10,7 @@ public class EditModeToolWindowEditor : Editor
 	public override void OnInspectorGUI()
 	{
 		if (EditorApplication.isPlayingOrWillChangePlaymode)
-		{
-			Selection.activeObject = null;
 			return;
-		}
```
Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:16]: This shouldn't have been removed, this was a fix

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs [hunk 5]
```diff
@@ -24,13 +24,8 @@ public static void ShowGUI(SceneView sceneView, bool haveOffset = true)
 				Rect  bottomBarRect;
 				if (haveOffset)
 				{
-#if UNITY_2021_2_OR_NEWER
-					bottomBarRect = new Rect(0, height - (CSG_GUIStyleUtility.BottomToolBarHeight + 27),
-						  width, CSG_GUIStyleUtility.BottomToolBarHeight);
-#else
 					bottomBarRect = new Rect(0, height - (CSG_GUIStyleUtility.BottomToolBarHeight + 18), 
 											  width, CSG_GUIStyleUtility.BottomToolBarHeight);
-#endif
```
Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs:33]: This was part of the other PR, are you sure this should've been removed?

Comment (LogicalError) [inline RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs:33]: Again, are you sure this should've been removed?

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs (hunk 4 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:16]: i thought i had changed that back. maybe i forgot to push the changes

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs (hunk 5 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/SceneViewBottomBarGUI/SceneViewBottomBar.GUI.cs:33]: yes. its not needed with changes from this PR, and does basically nothing as a result

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs (hunk 4 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/View/GUI/EditModeGUI/EditModeToolWindow.Editor.cs:16]: on checking this, i did indeed change it back, but git did not find the changes. should be fixed now

**Comment by Kerfuffles** [comment]
> Actually, I'm not sure if it's a good idea to commit all the ProjectSettings assets + ProjectVersion.txt since that will cause problems with older versions of unity

I would *like* to change the repo to a package, or to just the `Plugins/` folder. There seems to be a common confusion issue from others due to the entire repo being a project.

File: RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs (hunk 1 above)
Comment (Kerfuffles) [reply RealtimeCSG/Assets/Plugins/RealtimeCSG/Editor/Scripts/Control/Managers/SceneViewEventHandler.cs]: yeah. i haven't noticed any issues cropping up from this. keeping those two lines actually causes the toolbar to be drawn twice. once in the correct place, and again above it.

**Comment by LogicalError** [comment]
> > Actually, I'm not sure if it's a good idea to commit all the ProjectSettings assets + ProjectVersion.txt since that will cause problems with older versions of unity
> 
> I would _like_ to change the repo to a package, or to just the `Plugins/` folder. There seems to be a common confusion issue from others due to the entire repo being a project.

Fair enough, but addressing those issues would make more sense as a separate PR since we'd need to figure out how to best do this

**Comment by Kerfuffles** [comment]
> > > Actually, I'm not sure if it's a good idea to commit all the ProjectSettings assets + ProjectVersion.txt since that will cause problems with older versions of unity
> > 
> > 
> > I would _like_ to change the repo to a package, or to just the `Plugins/` folder. There seems to be a common confusion issue from others due to the entire repo being a project.
> 
> Fair enough, but addressing those issues would make more sense as a separate PR since we'd need to figure out how to best do this

Right. That was the plan. I may look into doing that at a later time, though.

**Comment by Kerfuffles** [comment]
I am basically done changing anything with this PR, if nothing else needs fixing/revision.

File: RealtimeCSG/ProjectSettings/ProjectVersion.txt [hunk 6]
```diff
@@ -1 +1,2 @@
-m_EditorVersion: 5.6.4f1
+m_EditorVersion: 2021.2.7f1
+m_EditorVersionWithRevision: 2021.2.7f1 (6bd9e232123f)
```
Comment (LogicalError) [inline RealtimeCSG/ProjectSettings/ProjectVersion.txt:2]: Can you revert this?
I'm fairly sure there are people who are using realtime-csg who are on older versions than 2021
upgrading is easier than downgrading.
Better yet, just delete the file

Comment (LogicalError) [reply RealtimeCSG/ProjectSettings/ProjectVersion.txt:2]: This would be the last issue

Comment (Kerfuffles) [reply RealtimeCSG/ProjectSettings/ProjectVersion.txt]: Done.

**Review by LogicalError — APPROVED** [review]
